export const FETCH_USER = 'fetch_user'
export const HANDLE_PAYMENT = 'handle_payment'
export const CHANGE_INPUT = 'change_input'
export const CREATE_SURVEY = 'create_survey'
export const FETCH_SURVEY = 'fetch_survey'
